RealCanteen/urls.py
from django.urls import path
from . import views

app_name='RealCanteen'

urlpatterns = [

    path('FoodContinental2/', views.FoodContinental2, name='FoodContinental2'),
    path('<str:slug>', views.food2_detailView, name = 'food2_detail'),

]

RiteCanteen/urls.py
from django.urls import path
from . import views

app_name='RiteCanteen'

urlpatterns = [
    path('index2/', views.index2, name = 'index2'),
    path('FoodContinental/', views.FoodContinental, name='FoodContinental'),
    path('<str:slug>', views.food_detailView, name = 'food_detail'),
    path('FoodFruit/', views.FoodFruit, name='FoodFruit'),
    path('FoodPastrils/', views.FoodPastrils, name='FoodPastrils'), 
    

]

RiteWeb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('coke/', views.coke, name = 'coke'),
    path('search/', views.searchR, name='searchR'),

    path('blog/<str:slug>', views.blog_detailView, name = 'blog_detail'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('About/', views.About, name='About'),
    path('EventPlan/', views.EventPlan, name='EventPlan'),
    path('EventWed/', views.EventWed, name='EventWed'),
    path('EventBirth/', views.EventBirth, name='EventBirth'),
    path('EventName/', views.EventName, name='EventName'),
    path('EventAnn/', views.EventAnn, name='EventAnn'),
    path('EventDiet/', views.EventDiet, name='EventDiet'),
    path('EventHot/', views.EventHot, name='EventHot'),
    path('EventCaf/', views.EventCaf, name='EventCaf'),
    path('EventRender/', views.EventRender, name='EventRender'),
    path('RitePhoto/', views.RitePhoto, name='RitePhoto'),
    path('StoreLocate/', views.StoreLocate, name='StoreLocate'),



]

Ritefood/urls.py
from django.contrib import admin
from django.urls import path
import RiteWeb
import RiteCanteen
import RealCanteen
import Alcholic
from django.contrib.auth import views as auth_views

from django.conf.urls import include

urlpatterns = [
    path('', include('RiteWeb.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('RealCanteen/', include('RealCanteen.urls')),
    path('RiteCanteen/', include('RiteCanteen.urls')),
    path('RiteDrink/', include('RiteDrink.urls')),
    path('Alcholic/', include('Alcholic.urls')),



# RESET PASSWORD URLS
path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
path('password_reset_sent',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

RiteCanteen/models.py
from email.mime import image
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
import os

    
    
def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.FoodSecondPage_id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.FoodSecondPage_id, ext)
    return os.path.join(upload_to, filename)





class Continental(models.Model):
    image = models.ImageField(upload_to = 'images_uploaded', null=True, blank=True)
    title = models.CharField(max_length = 250, null=True)
    body = models.TextField(max_length=500, null=True, blank=True)
    slug = models.SlugField()
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now = True, null=True)
    def __str__(self):
        return self.title



class Comment(models.Model):
    Commenter = models.CharField(max_length= 50)
    body = models.TextField()
    post2 = models.ForeignKey(Continental, on_delete= models.CASCADE, related_name= 'comments')
    def __str__(self):
        return self.body
    






class Fruit(models.Model):
    image = models.ImageField(upload_to = 'images_uploaded', null=True, blank=True)
    title = models.CharField(max_length = 200, null=True)
    body2 = models.TextField(max_length=500, null=True, blank=True)
    slug = models.SlugField(null=True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now = True, null=True)
    def __str__(self):
        return self.title
    




class Pastrils(models.Model):
    image = models.ImageField(upload_to = 'images_uploaded', null=True, blank=True)
    title = models.CharField(max_length = 200, null=True)
    body2 = models.TextField(max_length=500, null=True, blank=True)
    slug = models.SlugField(null=True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now = True, null=True)
    def __str__(self):
        return self.title


# class Drunk(models.Model):
#     image = models.ImageField(upload_to = 'images_uploaded', null=True, blank=True)
#     title = models.CharField(max_length = 200, null=True)
#     body2 = models.TextField(max_length=500, null=True, blank=True)
#     slug = models.SlugField(null=True)
#     writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
#     created_on = models.DateTimeField(auto_now = True, null=True)
#     def __str__(self):
#         return self.title


    

RiteCanteen/forms.py
from django import forms
from .models import Comment
from .models import Continental
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm





        

class CommentForm(forms.ModelForm):
    Commenter = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Your name'
        }))
    body = forms.CharField(max_length=100, widget = forms.Textarea(attrs={
        'class': 'form-control', 'placeholder': 'Comment here', 'rows':3
    }))
    class Meta:
        model = Comment
        fields = ['Commenter', 'body']
        

RiteCanteen/views.py
from django.shortcuts import render
from .forms import CommentForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from RiteWeb.forms import UserForm, UserProfileInfoForm
from django.views.generic import CreateView
# from .models import UserProfileInfo, Contact, AboutUs
from django.urls import reverse

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, DetailView, 
                                  ListView)
from .models import Continental, Fruit, Pastrils

# Create your views here.




def index2(request):
    return render(request,'base.html')

def FoodContinental(request):
    post2 = Continental.objects.all()
    return render(request, 'FoodContinental.html', {'posts': post2})

def food_detailView(request, slug):
    post2 = Continental.objects.get(slug = slug)
    comments = post2.comments.all()
    new_comment = None
      
    if request.method == 'POST':
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post2 = post2
            new_comment.save()
            return HttpResponseRedirect(reverse('RiteCanteen:food_detail', args = [str(post2.slug)]))
    else: 
        form = CommentForm()
    
    return render(request, 'food_detail.html', {'posts': post2, 'form': form,
                                                'comments': comments, 
                                                'new_comment':new_comment})
 


def FoodFruit(request):
    fish = Fruit.objects.all()
    return render(request, 'RiteCanteen/FoodFruit.html', {'fishs': fish})

def FoodPastrils(request):
    rites4 = Pastrils.objects.all()
    return render(request, 'RiteCanteen/FoodPastrils.html', {'rite': rites4})

RiteCanteen/templates/FoodContinental.html
{% extends 'continental.html' %}
{% load static %}
{% block title %} {% endblock %}

{% block content %}
<!-- section 1 for standards-->


<style>
 @import url(https://fonts.googleapis.com/css?family=Open+Sans:400, 300, 600, 700);

      html {
        font-family: "Open Sans", sans-serif;
      }
{% comment %}       
      h1 {
        color: #444;
      } {% endcomment %}




      .cup .btn {
        position: absolute;
        top: 40%;
        border-radius: 15px;

        left: 48%;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        font-size: 16px;
        padding: 12px 24px;
        cursor: pointer;
        text-align: center;
      }


      body {
        font-family: Arial;
        font-size: 17px;
      }
      
      .food {
        position: relative;
        max-width: 100%;
        margin: 0 auto;
      }
      
      .food img {vertical-align: middle;}
      
      .food .note {
        position: absolute;
        bottom: 0;
        background: rgb(0, 0, 0); /* Fallback color */
        background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
        color: #f1f1f1;
        width: 100%;
        padding: 20px;
      }



      .blink29 {
        animation: blinker 6s linear infinite;
        color: black;
      }
      @keyframes blinker {
        50% {
          opacity: 0;
        }
        
      }



      .glow98 {
        text-shadow: 0 0 5px gold, 0 0 10px gold,
        0 0 20px gold, 0 0 40px gold;
      }



      .glow01 {
        text-shadow: 0 0 5px darkGreen	, 0 0 10px darkGreen	,
        0 0 20px darkgreen	, 0 0 40px darkGreen	;
      }

      .navbar-toggler-icon {
        background-image: none!important;
        background-color: darkslategrey;
        height: 3px;
        width: 25px;
        margin: 10px 0;
        position: relative;
        transition: all 0.35s ease-out;
        transform-origin: center;
      }
      .navbar-toggler-icon::before {
        display: block;
        background-color: darkslategrey;
        height: 3px;
        content: "";
        position: relative;
        top: -7px;
        transition: all 0.15s ease-out;/*taken down to hide quicker*/
        transform-origin: center;
      }

      .navbar-toggler-icon::after {
        display: block;
        background-color: darkslategrey;
        height: 3px;
        content: "";
        position: relative;
        top: 4px;
  }


  .glow9 {
    text-shadow: 0 0 5px gold, 0 0 10px gold,
    0 0 20px gold, 0 0 40px gold;
  }
   
  .glow68 {
    text-shadow: 0 0 5px gold, 0 0 10px gold,
    0 0 20px gold, 0 0 40px gold;
  }   

  .glow977 {
    text-shadow: 0 0 5px white, 0 0 10px white,
    0 0 20px white, 0 0 40px white;
  }

  .blink9 {
    animation: blinker 6s linear infinite;
    color: yellow;
  }
  @keyframes blinker {
    50% {
      opacity: 0;
    }

  } 
  
  
    .blink90 {
      animation: blinker 6s linear infinite;
      color: orange;
    }
    @keyframes blinker {
      50% {
        opacity: 0;
      }  
    }



 .blink900 {
      animation: blinker 2s linear infinite;
    }
    @keyframes blinker {
      50% {
        opacity: 0;
      }  
    }


   .blink908 {
      animation: blinker 3s linear infinite;
    }
    @keyframes blinker {
      50% {
        opacity: 0;
      }  
    }

  </style>

    

<div class="container-fluid" style="background-color: teal">
  <br>
<div class="card text-center">
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner ">
      <div class="carousel-item active">
          <div class="food">
            <img height=350px src="https://i.postimg.cc/L51mDMj9/serve33.jpg" class="d-block w-100" alt="...">
            <div class="note">
              <h1 style="text-align: left"class="glow01">RITEDISHES</h1>
              <p style="text-align: left">We Offer The Best Meal You Can Ever Think Of</p>
            </div>
          </div>
        </div>
      <div class="carousel-item">
        <div class="food">
        <img height=350px src="https://i.postimg.cc/q72MVKRs/serve21.jpg" class="d-block w-100" alt="...">
        <div class="note">
          <h1 style="text-align: left"class="glow01">RITEDISHES</h1>
          <p style="text-align: left">Enjoy Our Tasty Meal 😋 </p>
        </div>
      </div>
      </div>
      <div class="carousel-item">
        <div class="food">
        <img height=350px src="https://i.postimg.cc/6qMTtYfZ/inter.jpg" class="d-block w-100" alt="...">
        <div class="note">
          <h1 style="text-align: left"class="glow01">RITEDISHES</h1>
          <p style="text-align: left">Enjoy Our Tasty Meal 😋 </p>
        </div>
      </div>
      </div>
      <div class="carousel-item">
        <div class="food">
        <img height=350px src="https://i.postimg.cc/Yq1zDnN8/delboy.gif" class="d-block w-100" alt="...">
        <div class="note">
          <h1 style="text-align: left"class="glow01">RITEDISHES</h1>
          <p style="text-align: left">Enjoy Free Delivery Of Any Food You Order From Us</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  </div>
</div>
  <br>
</div>

  <div style="background-color: teal">
    <h3 class="glow977" style="background-color: orange;font-weight:900; text-align:center; font-size: 28px">Inter-Continental Dishes</h3>
    <br>
  </div>
    
<div class="container-fluid" style="background-color: teal">

  <div class="card text-center">
    <div class=" cup">
      <img src="https://i.postimg.cc/W4Dss762/inter2.jpg" width="100%" class="img-fluid " alt="...">
      <a href="{% url 'RealCanteen:FoodContinental2' %}"><button type="button" class="btn btn-warning blink29 " ><span style="color: midnightblue; font-size: 20px; font-weight:900">View</span></button></a>
    </div>
    <div class="card-body">
      <h6 class="card-title glow98" style="color: midnightblue; font-weight:900; text-align: center; font-size: 25px">INTER-CONTINENTAL DISHES</h6>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <br>
</div>

</section>


  <section id="best-features" class="text-center">
  <div style="background-color: teal">
    <h3 class="glow977" style="background-color: orange;font-weight:900; text-align:center; font-size: 36px">Continental Dishes</h3>
    <br>
  </div>
    

</section>
<div class="container-fluid" style="background-color: teal">
    
  <div class="row row-cols-1 row-cols-md-2 g-4">
{% for post2 in posts %}
    <div class="col">
      <div class="card">
         </a>
        <a href="{% url 'RiteCanteen:food_detail' post2.slug %}"><img  width=200px, height=400px src="{{post2.image.url}}" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title" style="color: indigo; font-weight:900">{{post2.title}} </h5>   
            <small class="text-muted">🕗 3 mins ago </small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <br>
</div>
{%endblock%}