Alcholic/urls.py
from django.urls import path
from . import views

app_name='Alcholic'

urlpatterns = [

    path('FoodDrunk/', views.FoodDrunk, name='FoodDrunk'), 
    path('<str:slug>', views.Drank_detailView, name = 'Drank_detail'),


]

RiteDrink/urls.py
from django.urls import path
from . import views

app_name='RiteDrink'

urlpatterns = [
    

    path('FoodDrink/', views.FoodDrink, name='FoodDrink'),
    path('<str:slug>', views.drink_detailView, name = 'drink_detail'),


]

RiteWeb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('coke/', views.coke, name = 'coke'),
    path('search/', views.searchR, name='searchR'),

    path('blog/<str:slug>', views.blog_detailView, name = 'blog_detail'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('About/', views.About, name='About'),
    path('EventPlan/', views.EventPlan, name='EventPlan'),
    path('EventWed/', views.EventWed, name='EventWed'),
    path('EventBirth/', views.EventBirth, name='EventBirth'),
    path('EventName/', views.EventName, name='EventName'),
    path('EventAnn/', views.EventAnn, name='EventAnn'),
    path('EventDiet/', views.EventDiet, name='EventDiet'),
    path('EventHot/', views.EventHot, name='EventHot'),
    path('EventCaf/', views.EventCaf, name='EventCaf'),
    path('EventRender/', views.EventRender, name='EventRender'),
    path('RitePhoto/', views.RitePhoto, name='RitePhoto'),
    path('StoreLocate/', views.StoreLocate, name='StoreLocate'),



]

Ritefood/urls.py
from django.contrib import admin
from django.urls import path
import RiteWeb
import RiteCanteen
import RealCanteen
import Alcholic
from django.contrib.auth import views as auth_views

from django.conf.urls import include

urlpatterns = [
    path('', include('RiteWeb.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('RealCanteen/', include('RealCanteen.urls')),
    path('RiteCanteen/', include('RiteCanteen.urls')),
    path('RiteDrink/', include('RiteDrink.urls')),
    path('Alcholic/', include('Alcholic.urls')),



# RESET PASSWORD URLS
path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
path('password_reset_sent',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

RiteDrink/models.py
from email.mime import image
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
import os





class Drink(models.Model):
    image = models.ImageField(upload_to = 'images_uploaded', null=True, blank=True)
    title = models.CharField(max_length = 200, null=True)
    body2 = models.TextField(max_length=500, null=True, blank=True)
    slug = models.SlugField(null=True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
    created_on = models.DateTimeField(auto_now = True, null=True)
    def __str__(self):
        return self.title

class Comment(models.Model):
    Commenter = models.CharField(max_length= 50)
    body = models.TextField()
    rites5 = models.ForeignKey(Drink, on_delete= models.CASCADE, related_name= 'comments')
    def __str__(self):
        return self.body

RiteDrink/forms.py
from django import forms
from .models import Comment
from .models import Drink
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm





        

class CommentForm(forms.ModelForm):
    Commenter = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Your name'
        }))
    body = forms.CharField(max_length=100, widget = forms.Textarea(attrs={
        'class': 'form-control', 'placeholder': 'Comment here', 'rows':3
    }))
    class Meta:
        model = Comment
        fields = ['Commenter', 'body']
        

RiteDrink/views.py
from django.shortcuts import render
from .forms import CommentForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from RiteWeb.forms import UserForm, UserProfileInfoForm
from django.views.generic import CreateView
# from .models import UserProfileInfo, Contact, AboutUs
from django.urls import reverse

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, DetailView, 
                                  ListView)

# Create your views here.
from .models import Drink


def FoodDrink(request):
    rites5 = Drink.objects.all()
    return render(request, 'FoodDrink.html', {'rite': rites5})

def drink_detailView(request, slug):
    rites5 = Drink.objects.get(slug = slug)
    comments = rites5.comments.all()
    new_comment = None
      
    if request.method == 'POST':
        form  = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.rites5 = rites5
            new_comment.save()
            return HttpResponseRedirect(reverse('RiteDrink:drink_detail', args = [str(rites5.slug)]))
    else: 
        form = CommentForm()
    
    return render(request, 'drink_detail.html', {'rite': rites5, 'form': form,
                                                'comments': comments, 
                                                'new_comment':new_comment})

RiteDrink/templates/FoodDrink.html
{% extends 'drinkfile.html' %}
{% load static %}
{% block title %} {% endblock %}

{% block content %}
<!-- section 1 for standards-->


<style>
  @import url(https://fonts.googleapis.com/css?family=Open+Sans:400, 300, 600, 700);
 
       html {
         font-family: "Open Sans", sans-serif;
       }
 {% comment %}       
       h1 {
         color: #444;
       } {% endcomment %}
 
 
 
 
       .cup .btn {
         position: absolute;
         top: 40%;
         border-radius: 15px;
 
         left: 48%;
         transform: translate(-50%, -50%);
         -ms-transform: translate(-50%, -50%);
         font-size: 16px;
         padding: 12px 24px;
         cursor: pointer;
         text-align: center;
       }
 
 
       body {
         font-family: Arial;
         font-size: 17px;
       }
       
       .food {
         position: relative;
         max-width: 100%;
         margin: 0 auto;
       }
       
       .food img {vertical-align: middle;}
       
       .food .note {
         position: absolute;
         bottom: 0;
         background: rgb(0, 0, 0); /* Fallback color */
         background: rgba(0, 0, 0, 0.5); /* Black background with 0.5 opacity */
         color: #f1f1f1;
         width: 100%;
         padding: 20px;
       }
 
 
 
       .blink29 {
         animation: blinker 6s linear infinite;
         color: black;
       }
       @keyframes blinker {
         50% {
           opacity: 0;
         }
         
       }
 
 
 
       .glow98 {
         text-shadow: 0 0 5px gold, 0 0 10px gold,
         0 0 20px gold, 0 0 40px gold;
       }
 
 
 
       .glow01 {
         text-shadow: 0 0 5px darkGreen	, 0 0 10px darkGreen	,
         0 0 20px darkgreen	, 0 0 40px darkGreen	;
       }
 
       .navbar-toggler-icon {
         background-image: none!important;
         background-color: darkslategrey;
         height: 3px;
         width: 25px;
         margin: 10px 0;
         position: relative;
         transition: all 0.35s ease-out;
         transform-origin: center;
       }
       .navbar-toggler-icon::before {
         display: block;
         background-color: darkslategrey;
         height: 3px;
         content: "";
         position: relative;
         top: -7px;
         transition: all 0.15s ease-out;/*taken down to hide quicker*/
         transform-origin: center;
       }
 
       .navbar-toggler-icon::after {
         display: block;
         background-color: darkslategrey;
         height: 3px;
         content: "";
         position: relative;
         top: 4px;
   }
 
 
   .glow9 {
     text-shadow: 0 0 5px gold, 0 0 10px gold,
     0 0 20px gold, 0 0 40px gold;
   }
    
   .glow68 {
     text-shadow: 0 0 5px white, 0 0 10px white,
     0 0 20px white, 0 0 40px white;
   }  
   
   
   .glow98 {
    text-shadow: 0 0 5px orange, 0 0 10px orange,
    0 0 20px orange, 0 0 40px orange;
  }
 
   .glow977 {
     text-shadow: 0 0 5px white, 0 0 10px white,
     0 0 20px white, 0 0 40px white;
   }
 
   .blink9 {
     animation: blinker 6s linear infinite;
     color: yellow;
   }
   @keyframes blinker {
     50% {
       opacity: 0;
     }
 
   } 
   
   
     .blink90 {
       animation: blinker 6s linear infinite;
       color: orange;
     }
     @keyframes blinker {
       50% {
         opacity: 0;
       }  
     }
 
 
 
  .blink900 {
       animation: blinker 2s linear infinite;
     }
     @keyframes blinker {
       50% {
         opacity: 0;
       }  
     }
 
 
    .blink908 {
       animation: blinker 3s linear infinite;
     }
     @keyframes blinker {
       50% {
         opacity: 0;
       }  
     }
 
   </style>



<div style="background-color: teal">
  <h3 class="glow977" style="background-color: orange;font-weight:900; text-align:center; font-size: 36px">Alcholic Drink Categories</h3>
  <br>
</div>
  
<div class="container-fluid" style="background-color: teal">

<div class="card text-center">
  <div class=" cup">
    <img src="https://i.postimg.cc/v8xvgzNG/beer.jpg" width="100%" class="img-fluid " alt="...">
    <a href="{% url 'Alcholic:FoodDrunk' %}"><button type="button" class="btn btn-warning blink29 " ><span style="color: midnightblue; font-size: 20px; font-weight:900">View</span></button></a>
  </div>
  <div class="card-body">
    <h6 class="card-title glow98" style="color: midnightblue; font-weight:900; text-align: center; font-size: 25px">Alcholic Drinks</h6>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>
<br>
</div>

</section>




<section id="best-features" class="text-center">

  <div style="background-color: orange">
    <h3 class="glow68" style="background-color: orange;font-weight:900; text-align:center; font-size: 40px">Soft Drinks Categories</h3>
    <br>
  </div>
    

</section>
<div class="container-fluid" style="background-color: teal">
    
  <div class="row row-cols-1 row-cols-md-2 g-4">
{% for rites5 in rite %}
    <div class="col">
      <div class="card">
        <a href="{% url 'RiteDrink:drink_detail' rites5.slug %}"><img  width=200px, height=400px src="{{rites5.image.url}}" class="card-img-top" alt="..."></a>
        <div class="card-body">
          <h5 class="card-title" style="color: indigo; font-weight:900">{{rites5.title}} <span class="card-title" style="color: #2C3539; font-weight:900"> - ₦{{rites5.body2}}</span></h5>
            <small class="text-muted">🕗 3 mins ago </small>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <br>
</div>
{%endblock%}